baseURL = "https://peculiar.monster"
languageCode = "en-us"
title = "Peculiar Monster"
theme = "cactus"
copyright = "GigaMeow" # cactus will use title if copyright is not set
paginate = 1

# summaryLength = 200

# Main menu which appears below site header.

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Words"
url = "/posts"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Blogroll"
url = "/blogroll"
weight = 5

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]
  colortheme = "peculiar-monster" # dark, light, white, classic, peculiar-monster, or succulent
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = true # default
  fontawesome = true

  # Home page settings
  description = "Personal website, blah blah blah, more to come here."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagOverview = true # show category overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/CuriousMagpie" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post meta settings
  show_updated = true # default
  showReadTime = true # default
  showWordCount = true # default

  [[params.social]]
    name = "github"
    link = "https://github.com/CuriousMagpie"
  [[params.social]]
    name = "mastodon"
    link = "https://wandering.shop/@eilatan"
  [[params.social]]
    name = "discord"
    link = "https://discordapp.com/users/gigameow#9964"
  [[params.social]]
    name = "bookwyrm"
    link = "https://bookwyrm.social/user/peculiar-monster"
  [[params.social]]
    name = "rss"
    link = "https://peculiar.monster/index.xml"
