baseURL: "https://peculiar.monster/"
title: Peculiar Monster
author: Gigameow
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Peculiar Monster
  description: "Human being, coder in progress, science fiction nerd, and troublemaker. Call me GigaMeow."
  keywords: [blog, personal site]
  author: GigaMeow
  images: ["/logo.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: light
  disableThemeToggle: true
  colophon: true
  privacyStatement: true
  landAcknowledgement: true
  landAcknowledgementText: "Peculiar Monster is located in Delaware, the traditional lands of the Lenapehoking people."

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowCategory: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://peculiar.monster/favicon.ico"
    favicon16x16: "https://peculiar.monster/favicon-16x16.png"
    favicon32x32: "https://peculiar.monster/favicon-32x32.png"
    apple_touch_icon: "https://peculiar.monster/apple-touch-icon.png"
    safari_pinned_tab: "https://peculiar.monster/favicon.ico"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Peculiar Monster
    subtitle: "Human being, coder in progress, science fiction nerd, and troublemaker."
    imageUrl: "/logo.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: GigaMeow
    buttons:
      - name: Read Posts
        url: posts

  # home-info mode
  homeInfoParams:
    Title: "Peculiar Monster"
    Content: Human being, coder in progress, science fiction nerd, and troublemaker.

  socialIcons:
    - name: github
      url: 'https://github.com/CuriousMagpie'
    - name: mastodon
      url: 'https://wandering.shop/@eilatan'
    - name: discord
      url: 'https://discordapp.com/users/gigameow#9964'
    - name: goodreads
      url: 'https://www.goodreads.com/peculiar-monster'
    - name: rss
      url: 'https://peculiar.monster/posts/index.xml'

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 10
    - identifier: archives
      name: archives
      url: /archives/
      weight: 15
    - identifier: categories
      name: categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: blogroll
      name: blogroll
      url: /blogroll/
      weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

