baseURL: 'https://peculiar.monster/'
languageCode: en-us
title: Peculiar Monster
theme: peculiar-monster 
author: 'GigaMeow'
copyright: GigaMeow
paginate: 1

menu:
  main:
    - name: About
      url: /about
      weight: 1
    - name: Words
      url: /posts
      weight: 2
    - name: Categories
      url: /categories
      weight: 3
    - name: Tags
      url: /tags
      weight: 4
    - name: Blogroll
      url: /blogroll
      weight: 5

markup:
  tableOfContents:
    endLevel: 3
    ordered: true
    startLevel: 2
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: false
    noClasses: true
    style: dracula
    tabWidth: 4

params:
  colortheme: peculiar-monster
  rssFullText: true
  showAllPostsArchive: true
  fontawesome: true
  description: Human being, coder in progress, science fiction nerd, and troublemaker. Call me GigaMeow. 
  privacyStatementHeader: Peculiar Monster Privacy Statement
  privacyStatement: I'm not using analytics or other tracking methods. I am using CDNs for fonts and a CSS framework and those may use tracking, but I have no access to that information. Please respect my privacy.
  landAcknowledgement: Peculiar Monster is located in Delaware, the traditional lands of the Lenapehoking people.
  mainSection: posts
  showAllPostsOnHomePage: false
  postsOnHomePage: 5
  tagOverview: true
  showProjectsList: true
  projectsUrl: 'https://github.com/CuriousMagpie'
  dateFormat: '2006-01-02'
  show_updated: true
  showReadTime: true
  showWordCount: true
  
  social:
    - name: github
      link: 'https://github.com/CuriousMagpie'
    - name: mastodon
      link: 'https://wandering.shop/@eilatan'
    - name: discord
      link: 'https://discordapp.com/users/gigameow#9964'
    - name: bookwyrm
      link: 'https://bookwyrm.social/user/peculiar-monster'
    - name: rss
      link: 'https://peculiar.monster/posts/index.xml'
